version: '3'
services:
  api: # サービス名
    container_name: api
    build: ./docker # ビルドに使用する Dockerfile の場所
    tty: true # コンテナの永続化
    volumes:
      - ./api:/go/src/github.com/kenji-otomo/SNS-RECORD-API/api # マウントディレクトリ
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sns_record_api
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/initdb:/docker-entrypoint-initdb.d

